###
GET http://localhost:5000/

###
GET http://localhost:5000/review/4

###
GET http://localhost:5000/author/Hans Christian Andersen
###

GET http://localhost:5000/title/Things Fall Apart

###
POST http://localhost:5000/register
Content-Type: application/json

{
    "username":"Jon",
    "password":"Lovato11"
}

###
POST http://localhost:5000/customer/login
Content-Type: application/json

{
    "username":"Jon",
    "password":"Lovato11"
}

###
PUT http://localhost:5000/customer/auth/review/1
Content-Type: application/json

{
    "reviews":"Jon"
}

###
GET http://localhost:5000/cek

###
PUT http://localhost:5000/customer/johnsmith@gamil.com
Content-Type: application/json

{
    "firstName":"Jan",
    "lastName":"Lavito",
    "email":"janlavito@theworld.com",
    "DOB":"1/11/1991"
}
